#ifndef RTW_HEADER_graduation_project_prototype_collect_acc_types_h_
#define RTW_HEADER_graduation_project_prototype_collect_acc_types_h_
typedef struct P_graduation_project_prototype_collect_T_
P_graduation_project_prototype_collect_T ;
#endif
